---
- name: Install Python
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Install Python3
  hosts: all
  become: true
  tasks:
    - name: Install Python 3.x
      apt: "pkg={{ item }} state=latest"
      with_items:
        - python3
        - python3-venv
        - python3-dev
        - build-essential
      tags:
        - python3

- name: Install pyenv
  hosts: all
  become: false
  vars:
    - user: "{{ ansible_env.USER | default( 'ubuntu' ) }}"
  remote_user: "{{ user }}"
  tasks:
    - name: Get source code from git
      git:
        repo: "https://github.com/pyenv/pyenv.git"
        dest: "{{ ansible_env.HOME}}/.pyenv"

