---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: no
  become_user: root
  remote_user: vagrant
  vars:
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - zsh
    - pyenv
    - ros
    - customize
    - visual-studio-code
