---
# Setup bash

- name: Place a ~/.bash_profile
  become: false
  template:
    src: templates/.bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"

- name: Place a ~/dotfiles/shell/
  become: false
  file:
    path: "{{ ansible_env.HOME }}/dotfiles/shell"
    state: directory
