---
pyenv_git_repo: https://github.com/pyenv/pyenv.git

pyenv_root: ~/.pyenv
pyenv_project_root: '~'

pyenv_shell: /bin/bash
pyenv_runcom: ~/.bashrc

pyenv_versions: []
pyenv_default_versions: []
pyenv_project_versions: []

# pyenv_virtualenv: true
